version: '3.8'

services:
  app:
    container_name: 'app'
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 7314:7314
    stdin_open: true
    environment:
      - PORT=7314
    command: node server.js
volumes:
  node_modules: